### ISSUE TITLE
README link is not working: ui.skiff.com

### ISSUE THREAD

**Issue by romanr** [skiff-org/skiff-ui#275]
Not found it says.

**Comment by sammanjac** [comment]
I am having the same issue. Here is the screenshot of the same 
![scrnli_2_10_2023_9-42-54 AM](https://user-images.githubusercontent.com/591431/218119791-b54def03-8fdd-4c86-ae81-15c56ed7ded7.png)

**Comment by feynon** [comment]
Same issue. Is this project abandoned?

**Comment by mohitxskull** [comment]
Yeah not working

**Comment by mykytahryboedov** [comment]
Come on guys, let us touch the skiff ui

**Comment by romanr** [comment]
> Come on guys, let us touch the skiff ui

![monkeys-2001aspaceodyssey-gif](https://github.com/skiff-org/skiff-ui/assets/329079/df8bfdb3-2c81-4bd8-8562-ed54344a9335)

**Comment by jgdevelopment** [comment]
We're re-releasing this in the next week! Sneak peak below:

![CleanShot 2023-06-01 at 16 52 31@2x](https://github.com/skiff-org/skiff-ui/assets/3527315/d7c8b6c0-2c68-437a-9311-ba0e3772b9a6)

**Comment by jgdevelopment** [comment]
It's now https://skiff.com/ui
