### ISSUE TITLE
[NOD-310] [NOD-293] Text Area broken (tailwind css conflict)

### ISSUE THREAD

**Issue by skiff-shipwright** [skiff-org/skiff-ui#361]
<sub>From [SyncLinear.com](https://synclinear.com) | [NOD-293](https://linear.app/skiff/issue/NOD-293/text-area-broken-tailwind-css-conflict)</sub>

<sub>[NOD-310](https://linear.app/skiff/issue/NOD-310/[nod-293]-text-area-broken-tailwind-css-conflict)</sub>

**Comment by siddhakdak** [comment]
Can you please send me snapshot of that error so that i can start work on it.
